export enum EyeStyle {
  Closed = "closed",
  Closed2 = "closed2",
  Crying = "crying",
  Cute = "cute",
  Glasses = "glasses",
  Love = "love",
  Pissed = "pissed",
  Plain = "plain",
  Sad = "sad",
  Shades = "shades",
  SleepClose = "sleepClose",
  Stars = "stars",
  TearDrop = "tearDrop",
  Wink = "wink",
  Wink2 = "wink2",
}

export enum MouthStyle {
  Cute = "cute",
  Drip = "drip",
  FaceMask = "faceMask",
  KissHeart = "kissHeart",
  LilSmile = "lilSmile",
  Pissed = "pissed",
  Plain = "plain",
  Sad = "sad",
  Shout = "shout",
  Shy = "shy",
  Sick = "sick",
  SmileLol = "smileLol",
  SmileTeeth = "smileTeeth",
  TongueOut = "tongueOut",
  WideSmile = "wideSmile",
}
