import { Header } from "@/components/layout/Header";

import "./globals.css";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="ja">
      <body className="bg-gray-200">
        <div className="">
          <Header/>
          <main className="ml-auto w-10/12">{children}</main>
        </div>
      </body>
    </html>
  );
}
