import { Header } from "@/components/layout/header";

import "./globals.css";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="ja">
      <body className="bg-gray-200">
        <div className="flex">
          <Header />
          <main className="p-8">{children}</main>
        </div>
      </body>
    </html>
  );
}
